[package]
name = "atlas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
mathie = "0.3.1"
glium = "0.31"
earcutr = "0.2.0"
delaunator = { path = "../delaunator" }
