[package]
name = "ptya-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ptya-common = { path = "../ptya-common" }
log = "0.4"

glium = "0.31"
egui_glium = { path = "../egui_glium" }
egui =  {path = "../egui/egui"}

